name: sembast_cli_gui
description: A Flutter GUI application for viewing and querying Sembast databases using PlutoGrid
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sembast: ^3.7.4
  path_provider: ^2.1.1
  path: ^1.9.1
  
  pluto_grid: ^8.0.0
  
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

